// Desktop visual and interaction checks, using an isolated profile and no paid model requests.
process.env.AXON_QUIET_NOTIFICATIONS = '1';
const { app } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const assert = require('node:assert/strict');
const output = path.resolve(__dirname, '../test-results/interface-polish');
fs.mkdirSync(output, { recursive: true });
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'axon-polish-'));
app.setPath('userData', profile);
fs.writeFileSync(path.join(profile, 'window-state.json'), JSON.stringify({ maximized: false }));
app.commandLine.appendSwitch('disable-renderer-backgrounding');
app.commandLine.appendSwitch('disable-backgrounding-occluded-windows');
const pause = (ms) => new Promise((r) => setTimeout(r, ms));
const timeout = setTimeout(() => { console.error('POLISH_TIMEOUT'); app.exit(1); }, 90000);
app.on('browser-window-created', (_, win) => {
  win.show = () => { win.setPosition(-2400, 0); win.showInactive(); };
  win.setContentSize(1440, 900); win.webContents.setBackgroundThrottling(false);
  win.webContents.on('console-message', (_, details) => { if (details.level === 'error') console.error('UI_ERROR', details.message); });
  win.webContents.once('did-finish-load', async () => {
    const run = (code) => win.webContents.executeJavaScript(code);
    const wait = async (code, label) => { for (let i = 0; i < 200; i++) { if (await run(code)) return; await pause(100); } throw new Error('Timed out: ' + label); };
    const click = (selector) => run(`document.querySelector(${JSON.stringify(selector)}).click()`);
    const type = (selector, value) => run(`(() => {const el=document.querySelector(${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}));})()`);
    const snap = async (name) => { await pause(300); fs.writeFileSync(path.join(output, name + '.png'), (await win.webContents.capturePage()).toPNG()); };
    try {
      await wait(`!!document.querySelector('[aria-label="Office settings"]') && !document.querySelector('.office-loading')`, 'office ready');
      await run(`localStorage.setItem('axon.officeDebug','1')`);
      await click('[aria-label="Office settings"]');
      await wait(`!!document.querySelector('.settings')`, 'settings');
      for (const method of ['chatgptSignIn', 'chatgptSignOut', 'chatgptCancel', 'chatgptRefreshModels']) assert.equal(await run(`typeof window.axon.${method}`), 'function');
      await type('.settings-search input', 'keys'); await pause(150);
      assert.equal(await run(`document.querySelectorAll('.settings-nav [role=tab]').length`), 1);
      await type('.settings-search input', ''); await pause(150);
      await click('#settings-tab-appearance');
      await run(`[...document.querySelectorAll('[aria-label="Theme"] button')].find(b=>b.textContent.trim()==='Dark').click()`);
      await wait(`document.documentElement.dataset.theme==='dark'`, 'dark theme');
      await click('#settings-tab-accounts'); await wait(`!!document.querySelector('.subscription-grid')`, 'subscriptions');
      assert.equal(await run(`document.querySelectorAll('.subscription-card').length`), 2);
      await snap('accounts-dark');
      await run(`document.querySelectorAll('.subscription-card')[1].querySelector('.btn').click()`);
      await wait(`!!document.querySelector('.overlay-backdrop')`, 'Claude API key dialog');
      assert.equal(await run(`document.querySelector('.overlay input[type=password]').type`), 'password');
      await snap('api-key-dark'); await click('.overlay [aria-label="Close"]');
      await click('#settings-tab-models');
      await run(`document.querySelector('#settings-tab-models').focus(); document.querySelector('.settings-nav').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true,cancelable:true}))`);
      assert.equal(await run(`document.activeElement.id`), 'settings-tab-voice');
      await click('#settings-tab-models'); await pause(150);
      await run(`[...document.querySelectorAll('.settings-content button')].find(b=>b.textContent.includes('Add provider')).click()`);
      await wait(`!!document.querySelector('.overlay-backdrop')`, 'add provider dialog');
      assert.equal(await run(`document.querySelectorAll('[role=dialog]').length`), 2);
      await click('.overlay [aria-label="Close"]');
      await click('#settings-tab-appearance');
      await run(`[...document.querySelectorAll('[aria-label="Theme"] button')].find(b=>b.textContent.trim()==='Light').click()`);
      await wait(`document.documentElement.dataset.theme==='light'`, 'light theme');
      await click('#settings-tab-accounts'); await snap('accounts-light');
      await click('[aria-label="Close Settings"]');
      await run(`localStorage.setItem('axon.officeDebug','1'); [...document.querySelectorAll('.office-apps-menu button')].find(b=>b.textContent.trim()==='Team view').click()`);
      await wait(`!!document.querySelector('.office-roster-fallback')`, 'team view');
      await run(`[...document.querySelectorAll('.office-apps-menu button')].find(b=>b.textContent.trim()==='Office view').click()`);
      await wait(`!!window.__axonOffice && !document.querySelector('.office-loading')`, 'scene debug');
      await run(`(() => {const p=window.__axonOffice.deskPoint('frontend-developer');window.__axonOffice.focus(p.x,p.z,5);})()`);
      await pause(1200); await snap('office-detail');
      console.log('INTERFACE_POLISH_PASS: account cards, protected key dialog, searchable settings, keyboard tabs, both themes and office details');
      clearTimeout(timeout); app.exit(0);
    } catch (err) { console.error('POLISH_FAIL', err); console.error(await run(`JSON.stringify({dialogs:[...document.querySelectorAll('[role=dialog]')].map(e=>({class:e.className,text:e.textContent.slice(0,80)})),text:document.body.innerText.slice(-2000)})`)); await snap('failure'); clearTimeout(timeout); app.exit(1); }
  });
});
app.whenReady().then(() => require('../out/main/index.js'));
