import type { Skill, SkillSourceInfo } from '../shared/types';
import catalogJson from '../skills/catalog.json';
import bodiesJson from '../skills/bodies.json';

const skills = catalogJson.skills as Skill[];
const sources = catalogJson.sources as SkillSourceInfo[];
const bodies = bodiesJson as Record<string, string>;
const byId = new Map(skills.map((s) => [s.id, s]));

/** Bundled skill catalog. Read-only; regenerated by `npm run skills:ingest`. */
export function catalog(): { skills: Skill[]; sources: SkillSourceInfo[] } {
  return { skills, sources };
}
export function hasSkill(id: string): boolean {
  return byId.has(id);
}
/** Bodies for known ids, in the order given; unknown ids are skipped. */
export function skillBodies(ids: string[]): { id: string; name: string; source: string; body: string }[] {
  return ids.flatMap((id) => {
    const skill = byId.get(id);
    return skill && bodies[id] !== undefined ? [{ id, name: skill.name, source: skill.source, body: bodies[id] }] : [];
  });
}
